In [2]:
import pandas as pd

In [3]:
data = {'name' : ['sudh', 'krish','hitesh', 'tulesko'],
        'salary' : [100,200,300,400],
        'mail_id' :['sudh@ineuron.ai','krish@ineuron.ai','hitesh@ineuron.ai','tulesko@ineuron.ai'],
        'addr' : ['blr','blr','blr','mum']
        }

In [4]:
df55 = pd.DataFrame(data, index= [4,5,6,7]) 

In [5]:
df55.loc[5:6] #considers named index

name  salary            mail_id addr
5   krish     200   krish@ineuron.ai  blr
6  hitesh     300  hitesh@ineuron.ai  blr

In [6]:
df55.iloc[1:3] # consider default index

name  salary            mail_id addr
5   krish     200   krish@ineuron.ai  blr
6  hitesh     300  hitesh@ineuron.ai  blr

In [7]:
#df = pd.DataFrame(data, index= ['sudh', 'krish','hitesh', 'tulesko']) 

In [8]:
df

NameError: name 'df' is not defined

In [9]:
df = pd.DataFrame(data) 

In [10]:
df

name  salary             mail_id addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  blr
2   hitesh     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [11]:
data1= {'pf_nu' : [234,45,54465,656],
        'income_tax' : [234,565,767,6778],
        'mobile_no' : [23543,43543,454,5656],
        'courses' : ['ds' , 'bigdata' , 'web dev ' , 'blockchian']
       }

In [12]:
df1 = pd.DataFrame(data1)

In [13]:
df1

pf_nu  income_tax  mobile_no     courses
0    234         234      23543          ds
1     45         565      43543     bigdata
2  54465         767        454    web dev 
3    656        6778       5656  blockchian

In [14]:
df

name  salary             mail_id addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  blr
2   hitesh     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [15]:
#concatenation operation

In [16]:
pd.concat([df,df1]) #vertical concatenation( row wise)

name  salary             mail_id addr    pf_nu  income_tax  mobile_no  \
0     sudh   100.0     sudh@ineuron.ai  blr      NaN         NaN        NaN   
1    krish   200.0    krish@ineuron.ai  blr      NaN         NaN        NaN   
2   hitesh   300.0   hitesh@ineuron.ai  blr      NaN         NaN        NaN   
3  tulesko   400.0  tulesko@ineuron.ai  mum      NaN         NaN        NaN   
0      NaN     NaN                 NaN  NaN    234.0       234.0    23543.0   
1      NaN     NaN                 NaN  NaN     45.0       565.0    43543.0   
2      NaN     NaN                 NaN  NaN  54465.0       767.0      454.0   
3      NaN     NaN                 NaN  NaN    656.0      6778.0     5656.0   

      courses  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
0          ds  
1     bigdata  
2    web dev   
3  blockchian

In [17]:
pd.concat([df,df1], axis = 1) #horizontal concatenation( column wise)

name  salary             mail_id addr  pf_nu  income_tax  mobile_no  \
0     sudh     100     sudh@ineuron.ai  blr    234         234      23543   
1    krish     200    krish@ineuron.ai  blr     45         565      43543   
2   hitesh     300   hitesh@ineuron.ai  blr  54465         767        454   
3  tulesko     400  tulesko@ineuron.ai  mum    656        6778       5656   

      courses  
0          ds  
1     bigdata  
2    web dev   
3  blockchian

In [18]:
data2 = {'0' : ['sudh', 'krish','hitesh', 'tulesko'],
        '1' : [100,200,300,400],
        '2' :['sudh@ineuron.ai','krish@ineuron.ai','hitesh@ineuron.ai','tulesko@ineuron.ai'],
        '3' : ['blr','blr','blr','mum']
        }

In [19]:
data3= {'0' : [234,45,54465,656],
        '1' : [234,565,767,6778],
        '2' : [23543,43543,454,5656],
        '3' : ['ds' , 'bigdata' , 'web dev ' , 'blockchian']
       }

In [20]:
df2 = pd.DataFrame(data2)

In [21]:
df3 = pd.DataFrame(data3)

In [22]:
pd.concat([df2,df3]) # vertical concatenation(row wise)

0     1                   2           3
0     sudh   100     sudh@ineuron.ai         blr
1    krish   200    krish@ineuron.ai         blr
2   hitesh   300   hitesh@ineuron.ai         blr
3  tulesko   400  tulesko@ineuron.ai         mum
0      234   234               23543          ds
1       45   565               43543     bigdata
2    54465   767                 454    web dev 
3      656  6778                5656  blockchian

In [23]:
# Merge operations

In [24]:
data4 = {'emp_id' : [101,102,103,104],
         'salary' : [234,456,789,459],
         'pf' : [23,89,78,45]   
}

In [25]:
data5 = {'emp_id' : [101,102,104,105],
         'mob_no' : [3434,5656,767,878],
         'house_no' : [2433,438,758,454]   
}

In [26]:
df4 = pd.DataFrame(data4)

In [27]:
df5 = pd.DataFrame(data5)

In [28]:
df4

emp_id  salary  pf
0     101     234  23
1     102     456  89
2     103     789  78
3     104     459  45

In [29]:
df5

emp_id  mob_no  house_no
0     101    3434      2433
1     102    5656       438
2     104     767       758
3     105     878       454

In [30]:
pd.merge(df4,df5) #merge by default merges common data based on the common column name i.e emp_id

emp_id  salary  pf  mob_no  house_no
0     101     234  23    3434      2433
1     102     456  89    5656       438
2     104     459  45     767       758

In [31]:
pd.merge(df4,df5, how = 'left')

emp_id  salary  pf  mob_no  house_no
0     101     234  23  3434.0    2433.0
1     102     456  89  5656.0     438.0
2     103     789  78     NaN       NaN
3     104     459  45   767.0     758.0

In [32]:
pd.merge(df4,df5, how = 'right')

emp_id  salary    pf  mob_no  house_no
0     101   234.0  23.0    3434      2433
1     102   456.0  89.0    5656       438
2     104   459.0  45.0     767       758
3     105     NaN   NaN     878       454

In [34]:
pd.merge(df4,df5, how = 'right', on = 'emp_id')

emp_id  salary    pf  mob_no  house_no
0     101   234.0  23.0    3434      2433
1     102   456.0  89.0    5656       438
2     104   459.0  45.0     767       758
3     105     NaN   NaN     878       454

In [35]:
data6 = {'emp_id1' : [101,102,103,104],
         'salary' : [234,456,789,459],
         'pf' : [23,89,78,45]   
}

data7 = {'emp_id2' : [101,102,104,105],
         'mob_no' : [3434,5656,767,878],
         'house_no' : [2433,438,758,454]   
}

In [36]:
df6 = pd.DataFrame(data6)

In [37]:
df7 = pd.DataFrame(data7)

In [38]:
df6

emp_id1  salary  pf
0      101     234  23
1      102     456  89
2      103     789  78
3      104     459  45

In [39]:
df7

emp_id2  mob_no  house_no
0      101    3434      2433
1      102    5656       438
2      104     767       758
3      105     878       454

In [41]:
pd.merge(df6, df7, left_on= 'emp_id1', right_on= 'emp_id2')

emp_id1  salary  pf  emp_id2  mob_no  house_no
0      101     234  23      101    3434      2433
1      102     456  89      102    5656       438
2      104     459  45      104     767       758

In [49]:
data8 = {'emp_id' : [101,102,103,104],
         'salary' : [234,456,789,459],
         'pf' : [23,89,78,45]   
}

data9 = {'emp_id' : [101,102,104,105,123],
         'salary' : [234,456,789,459,234],
         'house_no' : [2433,438,758,454,5345]   
}

In [50]:
df8 = pd.DataFrame(data8)

In [51]:
df9 = pd.DataFrame(data9)

In [52]:
df8

emp_id  salary  pf
0     101     234  23
1     102     456  89
2     103     789  78
3     104     459  45

In [53]:
df9

emp_id  salary  house_no
0     101     234      2433
1     102     456       438
2     104     789       758
3     105     459       454
4     123     234      5345

In [54]:
pd.merge(df8, df9, on= ['emp_id', 'salary'])

emp_id  salary  pf  house_no
0     101     234  23      2433
1     102     456  89       438

In [55]:
# join operations

In [77]:
data10 = {'emp_id1' : [101,102,103,104],
         'salar1' : [234,456,789,459],
         'pf' : [23,89,78,45]   
}

data11 = {'emp_id2' : [101,102,104,105,123],
         'salary2' : [234,456,789,459,234],
         'house_no' : [2433,438,758,454,5345]   
}

In [78]:
df10 = pd.DataFrame(data10, index = ['a', 'b', 'c', 'd'])

In [79]:
df11 = pd.DataFrame(data11, index = ['a', 'b', 'd', 'e', 'f'])

In [80]:
df10

emp_id1  salar1  pf
a      101     234  23
b      102     456  89
c      103     789  78
d      104     459  45

In [81]:
df11

emp_id2  salary2  house_no
a      101      234      2433
b      102      456       438
d      104      789       758
e      105      459       454
f      123      234      5345

In [84]:
df10.join(df11) # join performs by default match on indexes(row) and merge is performed on column name

emp_id1  salar1  pf  emp_id2  salary2  house_no
a      101     234  23    101.0    234.0    2433.0
b      102     456  89    102.0    456.0     438.0
c      103     789  78      NaN      NaN       NaN
d      104     459  45    104.0    789.0     758.0

In [85]:
df10.join(df11, how= 'inner')

emp_id1  salar1  pf  emp_id2  salary2  house_no
a      101     234  23      101      234      2433
b      102     456  89      102      456       438
d      104     459  45      104      789       758

In [87]:
df_sales = pd.read_csv('sales_data_final.csv')

In [88]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

          category sub_category                 product_name sales quantity  \
0  Office Supplies      Storage          Tenex Lockers, Blue   408        2   
1  Office Supplies     Supplies     Acme Trimmer, High Speed   120        3   
2  Office Supplies      Storage      Tenex Box, Single Width    66        4   
3  Office Supplies        Paper  Enermax Note Cards, Premium    45        3   
4        Furniture  Furnishings   Eldon Light Bulb, Duo Pack   114        5   

   discount   profit  shipping_cost  order_priority  year  
0       0.0  106.140          35.46          Medium  2011  
1       0.1   36.036           9.72          Medium  2011  
2       0.0   29.640           8.17            High  2011  
3       0.5  -26.055           4.82            High  2011  
4       0.1   37.770           4.70          Medium  2011  

[5 rows x 21 columns]

In [92]:
def profit_flag(a) :
    if a >= 0:
        return 'positive'
    else:
        return 'negative'

In [93]:
profit_flag(55)

'positive'

In [94]:
profit_flag(-35)

'negative'

In [95]:
df_sales['flag_profit'] = df_sales['profit'].apply(profit_flag)

In [96]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sub_category  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...      Storage   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...     Supplies   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...      Storage   
3  Home Office        Stockholm     Sweden      EU    North  ...        Paper   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...  Furnishings   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year flag_profit  
0          35.46          Medium  2011    positive  
1           9.72          Medium  2011    positive  
2           8.17            High  2011    positive  
3           4.82            High  2011    negative  
4           4.70          Medium  2011    positive  

[5 rows x 22 columns]

In [99]:
df_sales[df_sales['flag_profit'] == 'positive']

order_id  order_date ship_date       ship_mode     customer_name  \
0        AG-2011-2040    1/1/2011  1/6/2011  Standard Class   Toby Braunhardt   
1       IN-2011-47883    1/1/2011  1/8/2011  Standard Class       Joseph Holt   
2        HU-2011-1220    1/1/2011  1/5/2011    Second Class     Annie Thurman   
4       IN-2011-47883    1/1/2011  1/8/2011  Standard Class       Joseph Holt   
5       IN-2011-47883    1/1/2011  1/8/2011  Standard Class       Joseph Holt   
...               ...         ...       ...             ...               ...   
51284  MX-2014-108574  12/31/2014  1/4/2015  Standard Class     Julia Barnett   
51285  CA-2014-115427  12/31/2014  1/4/2015  Standard Class        Erica Bern   
51286    MO-2014-2560  12/31/2014  1/5/2015  Standard Class         Liz Preis   
51287  MX-2014-110527  12/31/2014  1/2/2015    Second Class  Charlotte Melton   
51288  MX-2014-114783  12/31/2014  1/6/2015  Standard Class     Tamara Dahlen   

           segment             state        country  market   region  ...  \
0         Consumer       Constantine        Algeria  Africa   Africa  ...   
1         Consumer   New South Wales      Australia    APAC  Oceania  ...   
2         Consumer          Budapest        Hungary    EMEA     EMEA  ...   
4         Consumer   New South Wales      Australia    APAC  Oceania  ...   
5         Consumer   New South Wales      Australia    APAC  Oceania  ...   
...            ...               ...            ...     ...      ...  ...   
51284  Home Office        Tamaulipas         Mexico   LATAM    North  ...   
51285    Corporate        California  United States      US     West  ...   
51286     Consumer  Souss-Massa-Draƒ        Morocco  Africa   Africa  ...   
51287     Consumer           Managua      Nicaragua   LATAM  Central  ...   
51288     Consumer         Chihuahua         Mexico   LATAM    North  ...   

      sub_category                                     product_name sales  \
0          Storage                              Tenex Lockers, Blue   408   
1         Supplies                         Acme Trimmer, High Speed   120   
2          Storage                          Tenex Box, Single Width    66   
4      Furnishings                       Eldon Light Bulb, Duo Pack   114   
5            Paper          Eaton Computer Printout Paper, 8.5 x 11    55   
...            ...                                              ...   ...   
51284       Labels         Novimex Legal Exhibit Labels, Adjustable    17   
51285      Binders  Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl    14   
51286      Binders          Wilson Jones Hole Reinforcements, Clear     4   
51287       Labels           Hon Color Coded Labels, 5000 Label Set    26   
51288       Labels           Hon Legal Exhibit Labels, Alphabetical     7   

      quantity discount    profit  shipping_cost  order_priority  year  \
0            2      0.0  106.1400          35.46          Medium  2011   
1            3      0.1   36.0360           9.72          Medium  2011   
2            4      0.0   29.6400           8.17            High  2011   
4            5      0.1   37.7700           4.70          Medium  2011   
5            2      0.1   15.3420           1.80          Medium  2011   
...        ...      ...       ...            ...             ...   ...   
51284        3      0.0    0.6600           1.32          Medium  2014   
51285        2      0.2    4.5188           0.89          Medium  2014   
51286        1      0.0    0.4200           0.49          Medium  2014   
51287        3      0.0   12.3600           0.35          Medium  2014   
51288        1      0.0    0.5600           0.20          Medium  2014   

      flag_profit  
0        positive  
1        positive  
2        positive  
4        positive  
5        positive  
...           ...  
51284    positive  
51285    positive  
51286    positive  
51287    positive  
51288    positive  

[38747 rows x 22 columns]

In [103]:
df_sales['len_cust_name'] = df_sales['customer_name'].apply(len)

In [104]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year  flag_profit len_cust_name  
0          35.46          Medium  2011     positive            15  
1           9.72          Medium  2011     positive            11  
2           8.17            High  2011     positive            13  
3           4.82            High  2011     negative            12  
4           4.70          Medium  2011     positive            11  

[5 rows x 23 columns]

In [110]:
def quantity_flag(a) :
    if a < 5:
        return 'low'
    elif a> 5 and a <10:
        return 'medium'
    else:
        return 'high'

In [111]:
df_sales['seg_quantity'] = df_sales['quantity'].apply(quantity_flag)

In [113]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sales  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   408   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   120   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...    66   
3  Home Office        Stockholm     Sweden      EU    North  ...    45   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   114   

  quantity discount   profit shipping_cost  order_priority  year  flag_profit  \
0        2      0.0  106.140         35.46          Medium  2011     positive   
1        3      0.1   36.036          9.72          Medium  2011     positive   
2        4      0.0   29.640          8.17            High  2011     positive   
3        3      0.5  -26.055          4.82            High  2011     negative   
4        5      0.1   37.770          4.70          Medium  2011     positive   

   len_cust_name seg_quantity  
0             15          low  
1             11          low  
2             13          low  
3             12          low  
4             11         high  

[5 rows x 24 columns]

In [114]:
df_sales['square_qty'] = df_sales['quantity'].apply(lambda a : a**2) 

In [115]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... quantity  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...        2   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...        3   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...        4   
3  Home Office        Stockholm     Sweden      EU    North  ...        3   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...        5   

  discount   profit shipping_cost order_priority  year  flag_profit  \
0      0.0  106.140         35.46         Medium  2011     positive   
1      0.1   36.036          9.72         Medium  2011     positive   
2      0.0   29.640          8.17           High  2011     positive   
3      0.5  -26.055          4.82           High  2011     negative   
4      0.1   37.770          4.70         Medium  2011     positive   

   len_cust_name  seg_quantity square_qty  
0             15           low          4  
1             11           low          9  
2             13           low         16  
3             12           low          9  
4             11          high         25  

[5 rows x 25 columns]

In [117]:
# Numpy Library is derived from matLab

In [119]:
import numpy as np #numpy has array inbuilt

In [121]:
np.array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [124]:
type(np.array([2,3,4,5,6])) #n dimensional array 

numpy.ndarray

In [125]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
np.array([[1,2,3,4], [2,3,4,5]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [127]:
l = [[1,2,3,4], [2,3,4,5]]

l[0][0]

1

In [130]:
a = np.array([3,4,5,6,7], ndmin= 3)

In [131]:
a

array([[[3, 4, 5, 6, 7]]])

In [132]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [134]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [133]:
arr.ndim

2

In [135]:
# 3d array

In [137]:
np.random.randint(1,10,(4,4)) # 2d

array([[9, 3, 4, 2],
       [9, 7, 8, 6],
       [6, 7, 7, 8],
       [8, 3, 4, 8]])

In [143]:
np.random.randint(1,10,(4,4,2)) # 3d (z,y,x)

array([[[2, 9],
        [8, 9],
        [5, 5],
        [1, 1]],

       [[2, 4],
        [1, 1],
        [3, 2],
        [3, 8]],

       [[3, 5],
        [7, 9],
        [5, 8],
        [5, 4]],

       [[6, 2],
        [8, 7],
        [8, 6],
        [4, 4]]])

In [ ]:
# Task1  Fitbit
1. read this dataset in pandas mysql and mongodb
2. while creating a table in mysql dont use a manual approach to create it always use automation to create table in my sql
## Hint use csvkit library to automate
3. convert all dates available in dataset to timestamp format in pandas and in sql to datetime
4. find how many unique id we have
5. which is one of most active id that u have in whole data s


