In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5,6]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [4]:
l1 = [4,5,6,7,"sudh",34.565, True]

In [9]:
a1 = np.array(l1)

In [10]:
a2 = np.array([[1,2,3],[4,5,6]])

In [11]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [12]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [13]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [18]:
a1.ndim # basically dimension is axis in laymen term

1

In [19]:
a2.ndim

2

In [20]:
a3.ndim

3

In [21]:
a1.size # size indicates total no of elements

7

In [22]:
a2.size

6

In [24]:
a3.size

9

In [25]:
a1.shape 

(7,)

In [26]:
a2.shape # 2 rows and 3 columns

(2, 3)

In [27]:
a3.shape # 3 rows and 3 columns and 1 such matrix in z axis i.e. z,y,x 

(1, 3, 3)

In [44]:
np.random.randint(2,50, (3,4)) # 3 rows and 4 columns

array([[19, 28, 39, 27],
       [ 8, 47,  5, 48],
       [30, 26,  7, 27]])

In [45]:
np.random.randint(2,50, (2,3,4)) # 3 rows and 4 columns and 2 such matrix

array([[[ 9, 34, 15, 33],
        [23, 46, 42,  4],
        [10, 14, 36,  5]],

       [[40,  8, 26,  4],
        [43, 20, 22, 41],
        [16,  7, 16, 21]]])

In [49]:
np.random.rand(2,3) # it gives random data

array([[0.57535118, 0.06984922, 0.15318355],
       [0.1246723 , 0.86594118, 0.14433905]])

In [50]:
a4 = np.random.randn(4,4)  # randn gives data for normal distribution with mean = 0 and std.deviation = 1

In [51]:
a4

array([[ 0.32697995,  1.63398862, -0.14410738,  2.00757028],
       [-0.18150815,  0.01860244,  0.32624914,  0.881722  ],
       [ 1.04537696, -0.41000511,  0.28346933,  0.55694715],
       [-0.04950874, -0.18551815,  0.46862125,  0.33413481]])

In [52]:
a4.reshape(2,8)

array([[ 0.32697995,  1.63398862, -0.14410738,  2.00757028, -0.18150815,
         0.01860244,  0.32624914,  0.881722  ],
       [ 1.04537696, -0.41000511,  0.28346933,  0.55694715, -0.04950874,
        -0.18551815,  0.46862125,  0.33413481]])

In [53]:
a4.reshape(8,2)

array([[ 0.32697995,  1.63398862],
       [-0.14410738,  2.00757028],
       [-0.18150815,  0.01860244],
       [ 0.32624914,  0.881722  ],
       [ 1.04537696, -0.41000511],
       [ 0.28346933,  0.55694715],
       [-0.04950874, -0.18551815],
       [ 0.46862125,  0.33413481]])

In [54]:
a4.reshape(16,1)

array([[ 0.32697995],
       [ 1.63398862],
       [-0.14410738],
       [ 2.00757028],
       [-0.18150815],
       [ 0.01860244],
       [ 0.32624914],
       [ 0.881722  ],
       [ 1.04537696],
       [-0.41000511],
       [ 0.28346933],
       [ 0.55694715],
       [-0.04950874],
       [-0.18551815],
       [ 0.46862125],
       [ 0.33413481]])

In [56]:
a4.reshape(2,-1) # negative number detects second factor automatically

array([[ 0.32697995,  1.63398862, -0.14410738,  2.00757028, -0.18150815,
         0.01860244,  0.32624914,  0.881722  ],
       [ 1.04537696, -0.41000511,  0.28346933,  0.55694715, -0.04950874,
        -0.18551815,  0.46862125,  0.33413481]])

In [57]:
a4.reshape(2,2,4) # 2d to 3d conversion

array([[[ 0.32697995,  1.63398862, -0.14410738,  2.00757028],
        [-0.18150815,  0.01860244,  0.32624914,  0.881722  ]],

       [[ 1.04537696, -0.41000511,  0.28346933,  0.55694715],
        [-0.04950874, -0.18551815,  0.46862125,  0.33413481]]])

In [58]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [59]:
a1[0]

'4'

In [60]:
a1[2:6]

array(['6', '7', 'sudh', '34.565'], dtype='<U32')

In [61]:
a1[2:6:2]

array(['6', 'sudh'], dtype='<U32')

In [62]:
a1[::-1]

array(['True', '34.565', 'sudh', '7', '6', '5', '4'], dtype='<U32')

In [63]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
a2[0]

array([1, 2, 3])

In [66]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [67]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [68]:
a2[[0,1], 1:]

array([[2, 3],
       [5, 6]])

In [69]:
a5 = np.random.randint(2,90 , (6,5))

In [70]:
a5

array([[10, 79, 70, 88, 62],
       [84, 16, 50, 62, 60],
       [88, 45, 79, 37, 86],
       [83, 10,  5, 20, 48],
       [73, 23, 41, 30, 32],
       [88, 59,  2, 62, 40]])

In [71]:
a5[a5 > 40]

array([79, 70, 88, 62, 84, 50, 62, 60, 88, 45, 79, 86, 83, 48, 73, 41, 88,
       59, 62])

In [72]:
a5

array([[10, 79, 70, 88, 62],
       [84, 16, 50, 62, 60],
       [88, 45, 79, 37, 86],
       [83, 10,  5, 20, 48],
       [73, 23, 41, 30, 32],
       [88, 59,  2, 62, 40]])

In [76]:
a5[0,1] = 100

In [77]:
a5

array([[ 10, 100,  70,  88,  62],
       [ 84,  16,  50,  62,  60],
       [ 88,  45,  79,  37,  86],
       [ 83,  10,   5,  20,  48],
       [ 73,  23,  41,  30,  32],
       [ 88,  59,   2,  62,  40]])

In [83]:
a6 = np.random.randint(0,3 ,(3,3))

In [84]:
a7 = np.random.randint(0,3 ,(3,3))

In [85]:
a6

array([[2, 0, 1],
       [2, 0, 1],
       [1, 1, 1]])

In [86]:
a7

array([[1, 0, 1],
       [2, 0, 2],
       [0, 2, 2]])

In [88]:
a6 * a7 # it is multiplying element by element

array([[2, 0, 1],
       [4, 0, 2],
       [0, 2, 2]])

In [89]:
a6@a7  # this is matrix multiplication

array([[2, 2, 4],
       [2, 2, 4],
       [3, 2, 5]])

In [90]:
a6

array([[2, 0, 1],
       [2, 0, 1],
       [1, 1, 1]])

In [91]:
a6 + 100

array([[102, 100, 101],
       [102, 100, 101],
       [101, 101, 101]])

In [92]:
a6 * 2

array([[4, 0, 2],
       [4, 0, 2],
       [2, 2, 2]])

In [94]:
a6/0 # inf is infinity

C:\Users\Shubham\AppData\Local\Temp\ipykernel_3044\2812580279.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0 # inf is infinity
C:\Users\Shubham\AppData\Local\Temp\ipykernel_3044\2812580279.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0 # inf is infinity


array([[inf, nan, inf],
       [inf, nan, inf],
       [inf, inf, inf]])

In [95]:
a6 ** 3

array([[8, 0, 1],
       [8, 0, 1],
       [1, 1, 1]], dtype=int32)

In [98]:
a8 = np.zeros((4,4))

In [99]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [102]:
a9  = np.ones((4,5))

In [103]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [104]:
a9 + 10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [106]:
a9 + np.array([1,2,3,4,5]) #row-wise addition, this is row-wise broadcasting operation

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [107]:
a9 + np.array([1,2,3,4])

ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

In [113]:
np.array([1,2,3,4]).T # transpose cannot be done beacause only 1d needs 2d array

array([[1],
       [2],
       [3],
       [4]])

In [114]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [111]:
a9 + np.array([[1,2,3,4]]).T  # it is a transpose 

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [115]:
a6

array([[2, 0, 1],
       [2, 0, 1],
       [1, 1, 1]])

In [116]:
a6.T

array([[2, 2, 1],
       [0, 0, 1],
       [1, 1, 1]])

In [117]:
a5

array([[ 10, 100,  70,  88,  62],
       [ 84,  16,  50,  62,  60],
       [ 88,  45,  79,  37,  86],
       [ 83,  10,   5,  20,  48],
       [ 73,  23,  41,  30,  32],
       [ 88,  59,   2,  62,  40]])

In [118]:
np.sqrt(a5)

array([[ 3.16227766, 10.        ,  8.36660027,  9.38083152,  7.87400787],
       [ 9.16515139,  4.        ,  7.07106781,  7.87400787,  7.74596669],
       [ 9.38083152,  6.70820393,  8.88819442,  6.08276253,  9.2736185 ],
       [ 9.11043358,  3.16227766,  2.23606798,  4.47213595,  6.92820323],
       [ 8.54400375,  4.79583152,  6.40312424,  5.47722558,  5.65685425],
       [ 9.38083152,  7.68114575,  1.41421356,  7.87400787,  6.32455532]])

In [119]:
np.exp(a5)

array([[2.20264658e+04, 2.68811714e+43, 2.51543867e+30, 1.65163625e+38,
        8.43835667e+26],
       [3.02507732e+36, 8.88611052e+06, 5.18470553e+21, 8.43835667e+26,
        1.14200739e+26],
       [1.65163625e+38, 3.49342711e+19, 2.03828107e+34, 1.17191424e+16,
        2.23524660e+37],
       [1.11286375e+36, 2.20264658e+04, 1.48413159e+02, 4.85165195e+08,
        7.01673591e+20],
       [5.05239363e+31, 9.74480345e+09, 6.39843494e+17, 1.06864746e+13,
        7.89629602e+13],
       [1.65163625e+38, 4.20121040e+25, 7.38905610e+00, 8.43835667e+26,
        2.35385267e+17]])

In [120]:
np.log10(a5)

array([[1.        , 2.        , 1.84509804, 1.94448267, 1.79239169],
       [1.92427929, 1.20411998, 1.69897   , 1.79239169, 1.77815125],
       [1.94448267, 1.65321251, 1.89762709, 1.56820172, 1.93449845],
       [1.91907809, 1.        , 0.69897   , 1.30103   , 1.68124124],
       [1.86332286, 1.36172784, 1.61278386, 1.47712125, 1.50514998],
       [1.94448267, 1.77085201, 0.30103   , 1.79239169, 1.60205999]])

In [125]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [126]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
np.arange(1,10,2.5)

array([1. , 3.5, 6. , 8.5])

In [128]:
np.arange(1.7,10.9,2.5) # arange accepts floating point no.

array([1.7, 4.2, 6.7, 9.2])

In [132]:
np.linspace(2,3, num= 50) # in between 2 and 3 it generates 50 numbers

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [133]:
np.linspace(2,3, num= 50, retstep= True) # it gives jump space at last

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [134]:
np.logspace(2,4, num = 4, base = 10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [136]:
np.eye(5) # identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# plotly

In [139]:
#pip install cufflinks

In [140]:
import cufflinks as cf
import numpy as np
import pandas as pd
import seaborn as sns

In [141]:
cf.go_offline()

In [154]:
df = pd.DataFrame(np.random.randn(100,3), columns=  ['A', 'B', 'C'])

In [155]:
df

A         B         C
0   0.734021 -1.110471  1.356650
1   2.025875 -0.360136  0.040474
2   0.358670 -1.062465 -1.107419
3  -0.265445 -0.538572 -1.196220
4  -1.069374  0.120610  0.913915
..       ...       ...       ...
95 -0.155802  2.194126 -0.548927
96 -0.142310 -0.877951 -0.411164
97 -0.470643 -0.248922 -0.809116
98 -0.274458 -1.981754 -0.304843
99  0.092558 -1.498611  1.076975

[100 rows x 3 columns]

In [157]:
df.iplot() #y axis is column values and x axis is row index

In [147]:
df1 = pd.DataFrame(np.random.randint(3,100, (100,1)))

In [148]:
df1.head()

0
0  61
1  43
2  83
3  32
4  24

In [150]:
df1.iplot()

In [158]:
df.iplot(x = 'A', y = 'B', mode = 'markers') # Behaviour of A with respect to B

In [160]:
df2 = sns.load_dataset('titanic')

In [161]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [162]:
df2.iplot(x = 'age', y = 'fare', mode = 'markers')

In [165]:
df2.iplot(x = 'age', y = 'pclass', mode = 'markers')

In [167]:
df2.iplot(x = 'fare', y = 'pclass', mode = 'markers')

In [168]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [169]:
df2.iplot(kind = 'bar', x = 'sex', y = 'survived')